<?php

namespace App\Command;

use App\Repository\PlaylistDefinitionRepository;
use Cron\CronExpression;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'app:cron:dump',
    description: 'Print a supercronic-compatible crontab from enabled playlist definitions.',
)]
class DumpCronCommand extends Command
{
    public function __construct(
        private readonly PlaylistDefinitionRepository $repository,
        private readonly string $projectDir,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $output->writeln('# Generated by app:cron:dump on ' . (new \DateTimeImmutable())->format(DATE_ATOM));
        $output->writeln('# Re-run this command after editing playlist definitions.');
        $output->writeln('');

        $bin = $this->projectDir . '/bin/console';

        foreach ($this->repository->findScheduledEnabled() as $def) {
            $schedule = $def->getSchedule();
            if (!$schedule) {
                continue;
            }
            try {
                new CronExpression($schedule);
            } catch (\Throwable $e) {
                $output->writeln('# SKIP "' . $def->getName() . '": invalid schedule (' . $e->getMessage() . ')');
                continue;
            }

            $output->writeln(sprintf(
                '%s php %s app:playlist:run %d',
                $schedule,
                $bin,
                (int) $def->getId(),
            ));
        }

        return Command::SUCCESS;
    }
}
